#!/bin/bash

# Copyright (c) March 2013, Eric Andrew Bixler
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#	* Redistributions of source code must retain the above copyright
#	notice, this list of conditions and the following disclaimer.
#	* Redistributions in binary form must reproduce the above copyright
#	notice, this list of conditions and the following disclaimer in the
#	documentation and/or other materials provided with the distribution.
#	* Neither the name of the <organization> nor the names of its contributors
#	may be used to endorse or promote products derived from this software
#	without specific prior written permission.


###### Change The Following Variables:

## Note: It would be best to enable the option "Process only verified jobs" in SABnzbd under: Config --> Switches --> Post processing
## Note: make sure the XBMC web server is enabled

## XBMC details
xbmc-port="8090"
xbmc-ip="192.168.2.33"
xbmc-mac="BC:5F:F4:1D:8C:B4"
xbmc-pass="xbmc"
xbmc-user="xbmc"

## Set this to the IP of the machine running SABnzbd, 127.0.0.1 if its the same machine
downloader="192.168.2.104"

## What file-sharing protocol are we using for our remote/local shares; set to "smb", or "nfs" (others may work; havent tested them)
protocol="nfs"

## downloader scan paths
tv-path="export/_TV"
### uncategorized tv has no path to define, since we dont scan it to the library.
### we only send a visual notification to XBMC when SAB finishes an uncategorized download.
### examples include: out of season episodes; single episode specials, or newscast documentaries.
### these types of video are problematic when matching metadata with thetvdb.com, and are best left unidentified.
anime-path="export/_Anime"
archive-path="export/_To-Archive"
documentary-path="export/_Documentaries"
movie-path="export/_Movies"

## Set your categories from SABnzbd here
SAB-TV="tv"
SAB-Uncategorized-TV="uncat_tv"
SAB-Anime="anime"
SAB-Archive="archive"
SAB-Documentaries="documentaries"
SAB-Movies="movies"

## Set files to remove after SAB processing here
tv-garbage="nfo srt sfv srr url txt md5 diz jpg bmp png"
uncattv-garbage="nfo srt sfv srr url txt md5 diz jpg bmp png"
movie-garbage="sfv srr url txt md5 diz jpg bmp png"


#############################################
###### ATTENTION: DO NOT EDIT PAST THIS POINT
#############################################

pproc=$7
cat=$5
fpath=$1
cjob=$3
nzb=$2
grp=$6

success ()
{
	echo
	echo ">> Time Completed"
	echo "`date +"%A %b %e, %Y"`"
	echo "`date +"%r"`"
	echo
	echo "Success: Library Update Completed."
	exit 0
}

wake-failure ()
{
	echo
	echo ">> Time Failed"
	echo "`date +"%A %b %e, %Y"`"
	echo "`date +"%r"`"
	echo
	echo "Failed: Library Not Updated."
	echo "Failed: Issue: XBMC Didn't Respond to WOL Request."
	exit 1
}

processing-failed ()
{
	echo
	echo ">> Time Failed"
	echo "`date +"%A %b %e, %Y"`"
	echo "`date +"%r"`"
	echo
	echo "Failed: Library Not Updated."
	echo "Failed: Issue: SABnzbd Post-Processing Failure."
	exit 1
}

name-failed ()
{
	echo
	echo ">> Time Failed"
	echo "`date +"%A %b %e, %Y"`"
	echo "`date +"%r"`"
	echo
	echo "Failed: Library Not Updated."
	echo "Failed: Issue: Season/Episode Naming Scheme Undetectable."
	exit 1
}


###### Check Post-Processing Outcome From SAB

if [ "$7" -ge "1" ] ;
then
	echo
	echo "Error: SABnzbd Post-Processing Failed !"
	processing-failed
	## Failure, We're Exiting
fi


###### Define Junk Files & Set Video Category

if [ "$5" = "$SAB-TV" ] ;
then
	echo
	echo "[ TV ] Detected"
	echo
	garbage=$tv-garbage
	detec="1"
fi
if [ "$5" = "$SAB-Uncategorized-TV" ] ;
then
	echo
	echo "[ Uncategorized TV ] Detected"
	echo
	garbage=$uncattv-garbage
fi
if [ "$5" = "$SAB-Movies" ] ;
then
	echo
	echo "[ Movie ] Detected"
	echo
	garbage=$movie-garbage
	detec="0"
fi


###### Check For Proper Scene Naming Scheme, ex: s01e01, S01E01, etc.

echo "$2" | grep -o [S,s]*[[:digit:]][E,e,X,x]*[[:digit:]] > /dev/null
format="$?"
if [ "$detec" = "1" ] ;
then
	if [ "$format" = "1" ] ;
	then
		echo "$2"
		echo
		echo "Show Not Following A Recognizable Season/Episode Naming Standard"
		echo "Ex: s01e01, s01x02, 01x03, etc..."
		name-failed
		## Failure, We're Exiting
	fi
fi


###### Remove Junk Files

for junk in $garbage ;
do
	trash=$(find "$1" -name "*.$junk" 2> /dev/null)
	if [ ! -z $trash ] ;
	then
		nodisp=$(( nodisp + 1 ))
		if [ "$nodisp" -lt "2" ] ;
			echo ">> Junk Files Found"
		fi
		find "$1" -name *.$junk -type f -exec rm -f {} \;
		echo ">> .$junk Removed --> [ $trash ]"
		clean="0"
	fi
done
if [ "$clean" != "0" ] ;
then
	echo ">> No Junk Files Found"
	echo "Nothing Removed"
fi


###### Check if XBMC is Active

echo
attempt="0"

while true ;
do
	attempt=$(( attempt + 1 ))
	if [ "$attempt" = "7" ] ;
	then
		echo
		echo ">> XBMC Has Not Responded to WOL Packets."
		echo ">> Attempted To Wake XBMC [ 2 ] Times."
		echo ">> XBMC Has Failed to Wake"
		echo
		fail="1"
		break
	fi
	ping -c 4 $xbmc-ip > /dev/null 2>&1
	result=$?
	if [ "$result" = "1" ] ;
	then
		echo ">> XBMC Is Inactive"
		echo "Waking XBMC [ MAC: $xbmc-mac ]"
		wakeonlan $xbmc-mac > /dev/null 2>&1
		echo "Sleeping 100 seconds. "
		sleep 100
		echo "Timer Completed."
		echo "Retrying XBMC..."
		echo
		attempt=$(( attempt + 2 ))
		tried="1"
		continue
	else
		break
	fi
done


if [ "$result" = "0" ] ;
then
	if [ "$tried" = "1" ] ;
	then
		echo ">> XBMC Now Active"
		echo "Continuing"
		fail="0"
	else
		echo ">> XBMC Is Active"
		echo "Continuing"
		fail="0"
	fi
fi


###### TV Variables

show-name-and-season=$(echo "$1/" | awk -F/ '{print $(NF-2)"/"$(NF-1)}' | sed "s/\b\(.\)/\u\1/g" | sed 's/\/S/\/s/g')
show-name=$(echo `echo "$1/" | awk -F/ '{print $(NF-2)"/"$(NF-1)}'` | sed -e 's/\/.*//' | sed -e "s/\b\(.\)/\u\1/g")
show-season=$(echo "$1/" | awk -F/ '{print $(NF-1)}' | sed 's/s//')
show-episode=$(echo "$2/" | grep -o [S,s]*[[:digit:]][[:digit:]][E,e,X,x][[:digit:]][[:digit:]] | cut -c 4- | tr '[:upper:]' '[:lower:]' | sed 's/e//')


###### Movie Variables

movie-name-and-year=$(echo "$1/" | awk -F/ '{print $(NF-1)}' | sed -e "s/\b\(.\)/\u\1/g")
movie-name=$(echo "$1/" | awk -F/ '{print $(NF-1)}' | sed -e 's/([^()]*)//g' | sed -e "s/\b\(.\)/\u\1/g")
movie-year=$(echo "$1/" | awk '{print $NF}' | tr -d "/" | tr -d '()' )


debug ()
{
echo ">> Debuging Info"
if [ $detec = "1" ] ;
then
	echo "Show Name & Season...............: $show-name-and-season"
	echo "Show Name........................: $show-name"
	echo "Show Season......................: $show-season"
	echo "Show Episode.....................: $show-episode"
elif [ "$detec" = "0" ] ;
then
	echo "Movie Name & Year................: $movie-name-and-year"
	echo "Movie Name.......................: $movie-name"
	echo "Movie Year.......................: $movie-year"
fi
echo
echo ">> SABnzbd Data"
echo "SABnzbd Post-Processing..........: `if [[ "$pproc" -eq "0" ]]; then echo "Passed" ; else echo "Failed" ; fi` [ $pproc ]"
echo "User Defined Category............: $cat"
echo "Final Path of Job................: $fpath"
echo "NZB File(s) Name.................: $nzb"
echo "Clean Job Name...................: $cjob"
echo "Usenet Group.....................: $grp"
}


###### Update and Notify

if [ "$5" = "$SAB-TV" ] ;
then
	if [ "$fail" = "0" ] ;
	then
		echo
		echo ">> Sending GUI Notification"
		echo "curl -v -H \"Content-type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"GUI.ShowNotification\",\"params\":{\"title\":\" Library Update: TV\",\"message\":\" zzz\",\"image\":\"https://dl.dropbox.com/u/66962/Sab/sabnzbd_512.png\",\"displaytime\":10000}}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$show-name  [ s$show-season e$show-episode ]"'.g' | sh 2>/dev/null | cut -c 26- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
		echo ">> Updating Library --> [ TV ]"
		echo "Continuing"
		echo
		echo ">> (Re)Register: TV Show [ $show-name ] with XBMC Library"
		echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$tv-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$show-name"'.g' | sh 2>/dev/null | cut -c 30- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
		sleep 10
		echo ">> Adding: Season [ $show-season ] Episode [ $show-episode ] to XBMC Library"
		echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$tv-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$show-name-and-season"'.g' | sh 2>/dev/null | cut -c 30- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
	fi
	debug
	echo
	echo ">> Commands Run"
	echo
	echo "[ (Re)Register Show ]"
	echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$tv-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$show-name"'.g'""
	echo
	echo "[ Update Episode ]"
	echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$tv-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$show-name-and-season"'.g'""
	echo
elif [ "$5" = "$SAB-Uncategorized-TV" ] ;
then
	if [ "$fail" = "0" ] ;
	then
		echo
		echo ">> Sending GUI Notification"
		echo "curl -v -H \"Content-type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"GUI.ShowNotification\",\"params\":{\"title\":\" Library Update: TV-Uncat\",\"message\":\" zzz\",\"image\":\"https://dl.dropbox.com/u/66962/Sab/sabnzbd_512.png\",\"displaytime\":10000}}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"Uncategorized TV"'.g' | sh 2>/dev/null | cut -c 26- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
	fi
elif [ "$5" = "$SAB-Movies" ] ;
then
	if [ "$fail" = "0" ] ;
	then
		echo
		echo ">> Sending GUI Notification"
		echo "curl -v -H \"Content-type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"GUI.ShowNotification\",\"params\":{\"title\":\" Library Update: Movies\",\"message\":\" zzz\",\"image\":\"https://dl.dropbox.com/u/66962/Sab/sabnzbd_512.png\",\"displaytime\":10000}}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's/zzz/'"$movie-name-and-year"'/g' | sh 2>/dev/null | cut -c 26- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
		echo ">> Updating Library --> [ Movies ]"
		echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$movie-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$movie-name-and-year"'.g' | sh 2>/dev/null | cut -c 30- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
	fi
	debug
	echo
	echo ">> Command Run"
	echo
	echo "[ Register Movie ]"
	echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$movie-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$movie-name-and-year"'.g'""
	echo
elif [ "$5" = "$SAB-Documentaries" ] ;
then
	if [ "$fail" = "0" ] ;
	then
		echo
		echo ">> Sending GUI Notification"
		echo "curl -v -H \"Content-type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"GUI.ShowNotification\",\"params\":{\"title\":\" Library Update: Documentary\",\"message\":\" zzz\",\"image\":\"https://dl.dropbox.com/u/66962/Sab/sabnzbd_512.png\",\"displaytime\":10000}}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's/zzz/'"$movie-name-and-year"'/g' | sh 2>/dev/null | cut -c 26- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
		echo ">> Updating Library --> [ Documentaries ]"
		echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$documentary-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$movie-name-and-year"'.g' | sh 2>/dev/null | cut -c 30- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
	fi
	debug
	echo
	echo ">> Command Run"
	echo
	echo "[ Register Movie ]"
	echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$documentary-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$movie-name-and-year"'.g'""
	echo
elif [ "$5" = "$SAB-Archive" ] ;
then
	if [ "$fail" = "0" ] ;
	then
		echo
		echo ">> Sending GUI Notification"
		echo "curl -v -H \"Content-type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"GUI.ShowNotification\",\"params\":{\"title\":\" Library Update: Archive\",\"message\":\" zzz\",\"image\":\"https://dl.dropbox.com/u/66962/Sab/sabnzbd_512.png\",\"displaytime\":10000}}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's/zzz/'"$movie-name-and-year"'/g' | sh 2>/dev/null | cut -c 26- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
		echo ">> Updating Library --> [ Archive ]"
		echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$archive-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$movie-name-and-year"'.g' | sh 2>/dev/null | cut -c 30- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
	fi
	debug
	echo
	echo ">> Command Run"
	echo
	echo "[ Register Movie ]"
	echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$archive-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$movie-name-and-year"'.g'""
	echo
elif [ "$5" = "$SAB-Anime" ] ;
then
	if [ "$fail" = "0" ] ;
	then
		echo
		echo ">> Sending GUI Notification"
		echo "curl -v -H \"Content-type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"GUI.ShowNotification\",\"params\":{\"title\":\" Library Update: Anime\",\"message\":\" zzz\",\"image\":\"https://dl.dropbox.com/u/66962/Sab/sabnzbd_512.png\",\"displaytime\":10000}}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's/zzz/'"$movie-name-and-year"'/g' | sh 2>/dev/null | cut -c 26- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
		echo ">> Updating Library --> [ Anime ]"
		echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$anime-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$movie-name-and-year"'.g' | sh 2>/dev/null | cut -c 30- | sed -e 's/\":"/: /g' -e 's/["{}]//g'
		echo
	fi
	debug
	echo
	echo ">> Command Run"
	echo
	echo "[ Register Movie ]"
	echo "curl -s -H \"Content-Type: application/json\" -u $xbmc-user:$xbmc-pass -X POST -d '{\"jsonrpc\": \"2.0\", \"method\": \"VideoLibrary.Scan\", \"params\":{\"directory\":\"$protocol://$downloader/$anime-path/zzz/\"}, \"id\": \"scan\"}' http://$xbmc-ip:$xbmc-port/jsonrpc" | sed 's.zzz.'"$movie-name-and-year"'.g'""
	echo
fi

sleep 5

if [ "$fail" = "0" ] ;
then
	success
	## Success, We're Done
else
	## else will be equal to 1, as set by; fail="1" under "Check if XBMC is Active"
	wake-failure
	## Failure, We're Exiting
fi